[15기 GITOMP팀] Add : 로그인/회원가입 기능 구현
wecode-bootcamp-korea/15-1st-GITOMP-backend pull request #2
Opened 2020-12-17 06:36 UTC by seungjaekim-git

## 수정 사항 간략한 한줄 요약
- 로그인/회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
- 회원가입 기능 구현 (bcrypt로 비밀번호 암호화)
- 이메일/닉네임/비밀번호 형식에 맞춘 데이터 받도록 함
- 회원 닉네임 / 이메일 중복 제외 기능
- jwt 토큰을 이용한 인가 프로세스 구현
- 기타 에러 예외 처리
- 프론트와 통신 체크 완료

## 기타 질문 및 특이 사항
- @sunnu16 님과 같이 진행하였습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-17 07:07 UTC, soheon-lee commented on users/utils.py
> +JWT_ALGORITHM  = "HS256"
Token 암호화 알고리즘이 노출되었습니다. 보안에 굉장히 취약해지니 secret_key와 마찬가지로 별도의 모듈로 분리시켜 관리해주세요 :)

2020-12-17 07:07 UTC, soheon-lee commented on users/utils.py
> +
파이썬에서는 if 조건문을 평가하거나, 함수의 반환 되는 값 자체가 boolean 혹은 Truthy, Falsy 한 값일 경우,  `== False` `== None` `== 0`등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

2020-12-17 07:07 UTC, soheon-lee commented on users/utils.py
> +                token_payload = jwt.decode(token, SECRET_KEY, algorithms="HS256")
Token 암호화 알고리즘이 노출되었습니다. 보안에 굉장히 취약해지니 secret_key와 마찬가지로 별도의 모듈로 분리시켜 관리해주세요 :)

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +            assert is_valid(data['nickname'],NICKNAME_REGEX), "INVALID_NICKNAME_FORMAT"
```suggestion
            assert is_valid(data['email'], EMAIL_REGEX), "INVALID_EMAIL_FORMAT"
            assert is_valid(data['password'], PW_REGEX), "INVALID_PW_FORMAT"
            assert is_valid(data['nickname'], NICKNAME_REGEX), "INVALID_NICKNAME_FORMAT"
```
`,`콤마 뒤에는 간격 맞추시지 않으셔도 됩니다 :)

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +            hased_password = bcrypt.hashpw(data['password'].encode('utf-8'),bcrypt.gensalt())
```suggestion
            hashed_password = bcrypt.hashpw(data['password'].encode('utf-8'),bcrypt.gensalt())
```
오타인 것 같아요~

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +                                )
```suggestion
            User.objects.create(
                nickname=data['nickname'], 
                email=data["email"],
                password=hased_password.decode()
           )   
```
1. 이 형태가 조금 더 깔끔할 것 같네요 :)
2. `=` 기준으로 코드 정렬해주세요~

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +            return HttpResponse(status=201)
HttpResponse good! 201 good good !

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +
```suggestion

        try:
            user = User.objects.get(email=data['email'])            
            assert bcrypt.checkpw(data['password'].encode(),user.password.encode())            
            access_token = jwt.encode({"id":user.id},SECRET_KEY,algorithm=JWT_ALGORITHM)
            
            return JsonResponse({'MESSAGE':"SUCCESS",
                                 "NICKNAME":user.nickname,
                                 "TOKEN":access_token.decode()}, status=201)

```
로직이 크게 달라지지 않는다면 과다한 공백은 오히려 가독성을 해칠 수 있습니다 :) 짧은 함수라서 구분 많이 안하셔도 괜찮을 것 같습니다.
`:` 기준으로 코드 정렬해주세요

2020-12-17 07:07 UTC, soheon-lee commented on users/views.py
> +                             PW_REGEX, EMAIL_REGEX,  NICKNAME_REGEX
- 파이썬 자체 모듈
- Django 모듈
- 내가 만든 클래스

순서대로 import 하는 객체들을 정렬해주시고, 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요

2020-12-17 09:16 UTC, seungjaekim-git commented on users/utils.py
> +JWT_ALGORITHM  = "HS256"
아하 ~ 따로 처리했습니다 :)

2020-12-17 09:16 UTC, seungjaekim-git commented on users/utils.py
> +
```python3
def is_valid(text, regex):
    return re.complie(regex).match(text)
```
저 리턴 값이 none이면 false로 치환하기 때문에, 애초에 `!=`가 필요가 없었네요 ㅎ
이해했습니다 :+1:

2020-12-17 09:16 UTC, seungjaekim-git commented on users/utils.py
> +                token_payload = jwt.decode(token, SECRET_KEY, algorithms="HS256")
넵 !

2020-12-17 09:16 UTC, seungjaekim-git commented on users/views.py
> +            assert is_valid(data['nickname'],NICKNAME_REGEX), "INVALID_NICKNAME_FORMAT"
넵 ! 수정했습니다 :+1:

2020-12-17 09:16 UTC, seungjaekim-git commented on users/views.py
> +            hased_password = bcrypt.hashpw(data['password'].encode('utf-8'),bcrypt.gensalt())
넵 ! 수정했습니다 :+1:

2020-12-17 09:17 UTC, seungjaekim-git commented on users/views.py
> +                                )
넵 ! 수정했습니다 :+1:

2020-12-17 09:17 UTC, seungjaekim-git commented on users/views.py
> +            return HttpResponse(status=201)
thx :smile:

2020-12-17 09:18 UTC, seungjaekim-git commented on users/views.py
> +
넵 ! 수정했습니다 :+1:

2020-12-17 09:18 UTC, seungjaekim-git commented on users/views.py
> +                             PW_REGEX, EMAIL_REGEX,  NICKNAME_REGEX
```python
import json
import re
import bcrypt
import jwt

from django.http      import JsonResponse, HttpResponse
from django.views     import View
from django.db.models import Q

from users.models     import User
from my_settings      import SECRET_KEY, JWT_ALGORITHM
from users.utils      import LoginConfirm, is_valid, \
                             PW_REGEX, EMAIL_REGEX, NICKNAME_REGEX
```
흠...일단 이렇게 고쳤는데 users.models 는 장고에서 만든 모듈이니깐 장고 모듈 아닌가요??? 이 부분이 헷갈리네요 ㅠㅠ 제가 파일를 적은건 맞지만 장고에서 기본적으로 설치되는 파일이기도 해서 ... 그냥 제가 한번이라도 손 댄 파일은 "내가 만든 클래스"로 구분해야되나요 ???

2020-12-17 14:56 UTC, ulfrid requested changes
잘하셨네요 제거하실 한줄 제거해주시면 머지하겠습니다.

2020-12-17 14:56 UTC, ulfrid commented on users/views.py
> +
의미없는 빈줄 제거해주십시오

2020-12-18 00:38 UTC, seungjaekim-git commented on users/views.py
> +
넵 ! :+1:

2020-12-18 04:18 UTC, lordmyshepherd requested changes

2020-12-18 04:18 UTC, lordmyshepherd commented on users/utils.py
> +        except Users.DoesNotExist:
Class decorator로 구현해주셨네요! 깔끔하게 잘 만들어주신 것 같습니다.
하지만 로그인 데코레이터와 같은 경우, `클로저 함수`는 상태 정보 저장만을 목표로 할 때, 보다 가볍게 사용할 수 있는 좋은 방법입니다.
클로저 함수를 사용해서 구현해보시겠어요?

2020-12-18 04:18 UTC, lordmyshepherd commented on users/views.py
> +            assert is_valid(data['nickname'],NICKNAME_REGEX),"INVALID_NICKNAME_FORMAT"
assert문을 사용해보신 것 정말 좋네요~
다만, `파이썬에서 추구하는 코딩 스타일과 가독성 측면`에서, 다음과 같은 피드백을 드릴 수 있을 것 같습니다.
명확한 에러는 `if문으로 에러를 핸들링` 하도록 합니다.
 assert문을 사용하면 python이 error를 raise하게 되는점. 해당 에러를 확인하기 위해서 except문을 확인해야 된다는 점이
 이 가독성을 해칠 수 있습니다. 반대로, if문으로 분기처리를 할 경우, 가독성이 높이진다는 장점이 있습니다.
 
 예를 들어서,
 * if문을 활용한 에러 핸들링,
```
 if User.objects.filter().exists():
   return ...
```
* 파이썬이 error를 raise하고 try, except문을 이용해서 에러 핸들링 할 경우,
```
  try:
      user = User.objects.get()
  











  except User.MultipleObjectsReturned:
    return ...
```

assert문을 사용하지 않고 if문을 사용해서 분기처리 해주시는게 어떨까요?

2020-12-18 04:18 UTC, lordmyshepherd commented on users/views.py
> +            assert bcrypt.checkpw(data['password'].encode(),user.password.encode())
마찬가지에요~

2020-12-18 05:01 UTC, seungjaekim-git commented on users/utils.py
> +        except Users.DoesNotExist:
넵 ! 알겠습니다

2020-12-18 05:02 UTC, seungjaekim-git commented on users/views.py
> +            assert is_valid(data['nickname'],NICKNAME_REGEX),"INVALID_NICKNAME_FORMAT"
흠... 넵넵 !! 확실히 지금은 코드가 짧아서 괜찮지만, 몇백줄 되는 코드에서 해당 except 에러를 찾는것도 일이겠네요. 
알겠습니다! :+1:

2020-12-18 05:02 UTC, seungjaekim-git commented on users/views.py
> +            assert bcrypt.checkpw(data['password'].encode(),user.password.encode())
:+1:

2020-12-18 07:13 UTC, lordmyshepherd requested changes

2020-12-18 07:13 UTC, lordmyshepherd commented on users/views.py
> +                ).exists():
한 줄로 코드를 작성해 주셔도 충분히 가독성이 좋을 것 같습니다~

2020-12-18 07:13 UTC, lordmyshepherd commented on users/views.py
> +                },status=201)
sign-in은 정확히는 자원(resource)를 생성한 action은 아니기 때문에 status code는 200으로 맞춰주시면 될 것 같습니다.

2020-12-18 07:13 UTC, lordmyshepherd commented on users/utils.py
> +    return re.compile(regex).match(text)
하나의 함수에서 validation 검사를 하는게 오히려 가독성을 나쁘게 만들지 않나 생각이 드네요.
제 생각에는, 아래와 같이 각각에 함수의 명확한 역할에 맞게 나눠주시는게 좋을 것 같습니다.
이렇게하면, utils.py 모듈에 있는 정규식 상수들을 다시 views.py에 import 해주지 않아도 되겠죠?
```
def validate_email()

def validate_username()

def validate_password()
```

view에서도 line 20~ 26에서도 가독성이 더 좋아질 것 같아요!
제 개인적인 생각이에요~ 승재님 생각이 판단하셔서 수정하시거나 그대로 남겨두시면 될 것 같아요~

2020-12-18 07:13 UTC, lordmyshepherd commented on users/views.py
> +                },status=201)
한줄로 충분할 것 같습니다.
* acess_token을 반환 받았다는 의미에는 요청에 대해서 응답이 성공했음을 내포하고 있기 때문에 message : success는 불필요해 보입니다.
* 현재 서버에서 반환해주는 token이 어떤 토큰인지 명확히 해줄 필요가 있어 보입니다. 나중에는 refresh_token, csrf_token등 많은 값들을 관리해야될 상황이 올 수 있기 때문입니다~

```suggestion
            return JsonResponse({
                "nick_name" : user.nickname,
                "acess_token"    : access_token.decode()
                },status=201)
```

2020-12-18 07:56 UTC, seungjaekim-git commented on users/views.py
> +                ).exists():
넵 알겠습니다 !

2020-12-18 07:56 UTC, seungjaekim-git commented on users/views.py
> +                },status=201)
아하... 토큰을 생성하는 로직이 있어서 201이라고 생각했는데, 병민님 말씀처럼
[카카오 api](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token) 나 다른 api를 확인해도 토큰 생성은 200으로 하네요 ! 
알겠습니다 :smile:

2020-12-18 07:59 UTC, seungjaekim-git commented on users/views.py
> +                },status=201)
넵 !

2020-12-18 08:16 UTC, seungjaekim-git commented on users/utils.py
> +    return re.compile(regex).match(text)
넵 ! 병민님 말씀처럼 코드 가독성이 더 좋아질거 같아요. 
흠... 하지만, 지금 저렇게 만든 이유는 나중에 정규식을 수정할때 ,is_valid 함수와 정규식 자원을 따로따로 관리할 수 있어서 더 유연할거같아요.
이 부분은 제가 직접 한번 경험으로 느껴보는게 좋을거같아서, 1차 프로젝트는 기존의 방식대로하고 2차 프로젝트때는 병민님 의견을 수렴해서 한번 해보겠습니다 !
의견 감사합니다 :+1:

2020-12-18 08:30 UTC, lordmyshepherd approved these changes

2020-12-18 08:30 UTC, lordmyshepherd commented on users/utils.py
> +    return re.compile(regex).match(text)
좋아요! 👍 
팀원들이 보고 코드를 파악하는데 시간이 적게 걸리는 쪽으로 방향을 잡으시면 좋을 것 같아요~
🌈 감사합니다.

2020-12-18 08:33 UTC, lordmyshepherd commented
LGTM👍  
정말 고생 많으셨습니다! 

```
남겨드린 리뷰를 정확히 이해하시고, 잘 반영해주신점 👍 
```
```
코드와 답변에 왜(❓)가 있는 점 👍 
```

2020-12-18 08:34 UTC, merged