[15기 김승재] Add : 앨범 데이터 조회 기능 구현
wecode-bootcamp-korea/15-1st-GITOMP-backend pull request #3
Opened 2020-12-20 13:13 UTC by seungjaekim-git

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 메인페이지의 앨범 데이터 조회 api 구현
- 앨범 리스트 페이지 데이터 조회 api 구현
- 앨범 상세 내역 데이터 조회 api 구현
	 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- ```http://서버주소/albums/main-page```로 요청 시 각 카테고리별 4개의 앨범데이터 정보를 필요에 맞게 추출 [classic / jazz / newage / worldmusic / pop]
![image](https://user-images.githubusercontent.com/69844464/102713255-2ede8100-430a-11eb-8181-7a085bfb4eb7.png)
- prefetch_related을 활용하여 총 4개 QUERY만 발생
![image](https://user-images.githubusercontent.com/69844464/102713285-8b41a080-430a-11eb-80b1-65e8958c30c3.png)

- ```http://서버주소/albums```의 필터링 및 페이지네이션 구현
요청사항 parameter (Description)
1. year (해당 년도에 발매된 앨범 데이터 필터링)
2. genre (장르별 [classic,jazz,worldmusic,newage,pop] 데이터 필터링)
3. search_key (검색 카테고리 설정 [0 = 전체 / 1 = 제목 / 2 = 내용])
4. search (검색 단어 입력시 검색 카테고리와 비교하여 필터링하고자하는 field에서 데이터 필터링)
5. page (해당 페이지에 해당하는 앨범 데이터 리스트 추출)

![image](https://user-images.githubusercontent.com/69844464/102713408-6699f880-430b-11eb-8d80-122f21cb758f.png)

- prefetch 와 select_related을 활용하여 db query 가 2개만 발생
![image](https://user-images.githubusercontent.com/69844464/102713439-977a2d80-430b-11eb-881b-dd02b4f01b36.png)

- ```http://서버주소/albums/album_pk``` 요청 시 해당 album_pk에 해당하는 상세정보 응답 + 다음 /이전 앨범 데이터도 존재한다면 포함 (pk 기준) 

![image](https://user-images.githubusercontent.com/69844464/102713477-db6d3280-430b-11eb-9aeb-5d95017675e0.png)

- prefetch와 select문을 사용하였지만, 총 13개의 Query가 발생 
1. 상세내용을 표시하는 앨범 id와 동일한 앨범데이터 요청 (1)
2. 해당 앨범의 아티스트,수록곡,플레이링크 (최대 5개)[melon, bugs, flo, vibe, gennie]카테고리 요청 (3)
3. 다음 앨범이 있을때, 다음 앨범 데이터 요청 및 해당 앨범의 아티스트 데이터 요청 (2)
4. 이전 앨범이 있을때, 이전 앨범 데이터 요청 및 해당 앨범의 아티스트 데이터 요청 (2)
5. 플레이링크와 앨범의 중간테이블에 존재하는 url 데이터 요청시 (5)

![image](https://user-images.githubusercontent.com/69844464/102713708-803c3f80-430d-11eb-9262-7cf0b3217509.png)

- 메인페이지에 cd 이미지가 있다는 것을 테이블짤 때 생각하지 못해서 cd_image_url field를 Album 모델에 추가
- 프론트 분들이 해당 cd를 돌리는 모션을 하셔야 되서 cd 주위에 배경이 없어야 된다고 하셔서 찾아보았지만, 배경이 아예없는 cd 이미지를 찾기 어려웠습니다.
- 그래서 다른 프론트 팀원이 cd 이미지 하나의 배경을 없애시고 그걸 제 서버에서 요청하는 식으로 할려고, static directory를 추가하였습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 앨범 리스트 뷰를 구현하면서 가독성을 높이려고 이것저것 해보았지만, 아직 많이 부족한거 같습니다 ㅠㅠ 만약 읽으시다가 난해한 부분이 있으면 피드백 부탁드려요 !
- 아직 제가 ManytoMany field 에서 데이터 조회를 할 때, query를 많이 쓰는거 같네요 ㅠ 예를 들어서, 앨범 상세내용에서 각 플레이링크에 대한  url 정보를 가져오는데 5개면 5개의 query를 요청하고 있습니다. 이 부분이 아직 미숙한거 같아서 혹시 다른 방향이 있다면 피드백 부탁릅니다 :smiley:  

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-21 04:11 UTC, soheon-lee commented
와ㅏㅏㅏ 싱어송라이터ㅓㅓㅓㅓㅓ 감사합니다 승재님 ㅋㅋㅋ
![image](https://user-images.githubusercontent.com/42701133/102738616-00a28500-438e-11eb-9c41-ff8f30b5bd97.png)
체크리스트 예쁜 체크 박스가 될 수 있도록 수정 해주세요-!

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +        page        = int(request.GET.get('page',1))
프론트에서 페이지 수 쿼리스트링으로 받아오시는군요 gooood!

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +        ALBUM_COUNT = 10
한 번에 몇 개를 가져올건지도 프론트에서 가져올 수 있도록 flexible하게 해주시는 것을 추천드립니다.
혹시 바로 적용하기 어렵다면 현재와 같은 상수도 좋습니다 👍

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +        offset      = limit - ALBUM_COUNT
```suggestion
        limit       = ALBUM_COUNT * page
        offset      = limit - ALBUM_COUNT
```
아래 offset 해주신 것 처럼 변수와 연산자 사이는 띄우시는 것이 좋습니다

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +        albums = Album.objects.select_related('genre','release_type').prefetch_related('artist').filter(query,**filter_set)
dictionary unpacking gooood!

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +                query &= Q(description__icontains=search_string)
search_key로 들어오는 숫자와 필터링 하는 조건이 1:1로 매치된다면
if/else 구문보다 dictionary를 활용해보면 어떨까요?

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +        if not len(albums):
```suggestion
        if not albums:
```
albums가 queryset이므로, 길이로 판별하셔도 좋지만, queryset자체가 내부에 그 어떤 객체도 포함되어 있지 않으면 Falsy한 값이 됩니다 :) 따라서 len 없이 바로 not 구문을 사용하실 수 있습니다

2020-12-21 04:22 UTC, soheon-lee commented on albums/views.py
> +                "release_date": album.release_date
여기 `:`를 기준으로 정렬해주세요 :)

2020-12-21 04:31 UTC, seungjaekim-git commented on albums/views.py
> +        page        = int(request.GET.get('page',1))
thx :smile:

2020-12-21 04:32 UTC, seungjaekim-git commented on albums/views.py
> +        ALBUM_COUNT = 10
아하 ... offset과 limit 을 프론트에서 입력해야지 유동적으로 되겠군요 ... 생각하지 못했던 부분이네요 ! 
다른 작업하는게 마치는대로 수정하겠습니다 :+1:

2020-12-21 04:36 UTC, seungjaekim-git commented on albums/views.py
> +        offset      = limit - ALBUM_COUNT
넵 !

2020-12-21 04:37 UTC, seungjaekim-git commented on albums/views.py
> +        albums = Album.objects.select_related('genre','release_type').prefetch_related('artist').filter(query,**filter_set)
ㅎㅎ :smile:

2020-12-21 04:38 UTC, seungjaekim-git commented on albums/views.py
> +        if not len(albums):
아! 이해됐습니다. 감사합니다. :+1:

2020-12-21 04:39 UTC, seungjaekim-git commented on albums/views.py
> +                "release_date": album.release_date
넵 :+1:

2020-12-21 04:48 UTC, seungjaekim-git commented on albums/views.py
> +                query &= Q(description__icontains=search_string)
```python
 search_option = {
            0 : Q(title__icontains=search_string) | Q(description__icontains=search_string),
            1 : Q(title__icontains=search_string),
            2 : Q(description__icontains=search_string)
        }


        if search_string:
            if not search_key:
                search_key = 0
            query &= search_option[search_key]
```

의견 감사합니다. 더 깔끔해서 좋은거같아요 :+1:

2020-12-21 04:51 UTC, lordmyshepherd requested changes

2020-12-21 04:51 UTC, lordmyshepherd commented on albums/views.py
> +class ListView(View):
어떤 resource의 list view 인지 명시해주는게 좋을 것 같습니다.

```suggestion
class AlbumㄴView(View): 
또는
class AlbumListView(View): 
```

2020-12-21 04:51 UTC, lordmyshepherd commented on albums/views.py
> +            "page_count" : page_count,
page_count는 뭔가요?

2020-12-21 04:51 UTC, lordmyshepherd commented on albums/views.py
> +                    "link_url"  : AlbumPlayLink.objects.get(album=album.id,play_link=playlink.id).url
여기서도 error 발생할 수 있겠네요.
```suggestion
                    "link_url"  : AlbumPlayLink.objects.get(album=album.id,play_link=playlink.id).url
```

2020-12-21 04:51 UTC, lordmyshepherd commented on albums/views.py
> +                    "link_url"  : AlbumPlayLink.objects.get(album=album.id,play_link=playlink.id).url
db를 매번 조회하는 이유가 여기에 있네요. 여기서 `AlbumPlatLink`로 다시 조회하는 이유가 있나요?

2020-12-21 08:03 UTC, seungjaekim-git commented on albums/views.py
> +class ListView(View):
넵 수정하겠습니다 !

2020-12-21 08:06 UTC, seungjaekim-git commented on albums/views.py
> +            "page_count" : page_count,
page count는 페이지 갯수입니다
필터링을 거치고 난 후 나오는 앨범 갯수 기준으로 몇 페이지가 나오는지 알려주는 데이터입니다. (p.s 한 페이지당 10개의 앨범을 보여주기로 프론트분들이랑 얘기했습니다.)

2020-12-21 08:44 UTC, seungjaekim-git commented on albums/views.py
> +                    "link_url"  : AlbumPlayLink.objects.get(album=album.id,play_link=playlink.id).url
![image](https://user-images.githubusercontent.com/69844464/102756085-b253ad00-43b2-11eb-80df-7b38a0516eb4.png)
이부분을 공부하고 지금 해결했습니다. prefetch를 통해서 해당 playlink table 정보를 캐싱하는데 까지는 성공했는데, 가운데 테이블에 있는 url 정보를 빼와야되었기 때문에 어떻게 해야지 가운데 테이블과 playlink 테이블을 동시에 조회하면서 데이터를 맞추느냐하면서 찾아보았고,  밑의 코드 처럼 zip()을 활용해서 DB에 쏘는 퀘리를 고정적으로 8개까지 줄이는데 성공했습니다. ㅎㅎ
```python
"playlinks"          : [{
                    "link_name" : playlink.name,
                    "link"      : album_playlink.url
                }for (playlink,album_playlink) in zip(album.play_link.all(),album.albumplaylink_set.all())]
```
![image](https://user-images.githubusercontent.com/69844464/102756645-913f8c00-43b3-11eb-8b25-094fdf01f49e.png)

상세내용을 표시하는 앨범 id와 동일한 앨범데이터 요청 (1)
해당 앨범의 아티스트,수록곡,플레이링크 (최대 5개)[melon, bugs, flo, vibe, gennie]카테고리 요청 (3)
다음 앨범이 있을때, 다음 앨범 데이터 요청 및 해당 앨범의 아티스트 데이터 요청 (2)
이전 앨범이 있을때, 이전 앨범 데이터 요청 및 해당 앨범의 아티스트 데이터 요청 (2)
__플레이링크와 앨범의 중간테이블에 존재하는 url 데이터 요청시 (0)__
이렇게 총 8개의 쿼리만 고정적으로 발생하는 것을 확인하였습니다
:+1:

2020-12-21 08:46 UTC, seungjaekim-git commented on albums/views.py
> +                    "link_url"  : AlbumPlayLink.objects.get(album=album.id,play_link=playlink.id).url
이 부분을 밑에 다음 COMMENT에 해주신 내용처럼 수정하여서, ```AlbumPlayLink.DoesNotExist```와 같은 에러는 발생하지 않도록 하였습니다 !
:+1:

2020-12-22 07:35 UTC, lordmyshepherd approved these changes

2020-12-22 07:35 UTC, lordmyshepherd commented
LGTM 👍 
고생 많으셨습니다. 승재님, 선우님.
다음부터는 각자 올려주시면 더 완벽한 팀워크가 될 것 같아요~

2020-12-22 07:35 UTC, merged